# Google Cloud Run configuration
service: yolov5-webapp
runtime: python312

instance_class: F2

env_variables:
  PYTHONUNBUFFERED: "1"

automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
