steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/yolov5-webapp", "."]

  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/yolov5-webapp"]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "yolov5-webapp"
      - "--image"
      - "gcr.io/$PROJECT_ID/yolov5-webapp"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--memory"
      - "2Gi"
      - "--cpu"
      - "2"
      - "--timeout"
      - "300"

images:
  - "gcr.io/$PROJECT_ID/yolov5-webapp"
